parameters:
    twilio_account_sid: '%env(TWILIO_ACCOUNT_SID)%'
    twilio_auth_token: '%env(TWILIO_AUTH_TOKEN)%'
    twilio_number: '%env(TWILIO_NUMBER)%'

services:
    App\Service\NotificationService:
        arguments:
            $client: '@twilio.client'
           # $from: '%twilio_number%'

    twilio.client:
        class: Twilio\Rest\Client
        arguments:
            - '%twilio_account_sid%'
            - '%twilio_auth_token%'

    Twilio\Rest\Client: '@twilio.client'

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
