framework:
    validation:
        enable_attributes: true # Ensure annotations are enabled
        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        auto_mapping:
            App\: ~

when@test:
    framework:
        validation:
            not_compromised_password: false
